// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBHlVtdqEHy7LyGsBPPNnylRxbV8nBjB0',
    appId: '1:481537812306:web:029f26ada45b2d238b3c8b',
    messagingSenderId: '481537812306',
    projectId: 'apec-no-dues',
    authDomain: 'apec-no-dues.firebaseapp.com',
    storageBucket: 'apec-no-dues.firebasestorage.app',
    measurementId: 'G-ZPVRNXPE82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0WI0shd4PW2VNwle8_xT2-2pGMpP7kvs',
    appId: '1:481537812306:android:11c07e534ee9ec568b3c8b',
    messagingSenderId: '481537812306',
    projectId: 'apec-no-dues',
    storageBucket: 'apec-no-dues.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYVItWTIh3n99sQOu21FSkR3c9CTY_4bQ',
    appId: '1:481537812306:ios:ef13a5af01f326cc8b3c8b',
    messagingSenderId: '481537812306',
    projectId: 'apec-no-dues',
    storageBucket: 'apec-no-dues.firebasestorage.app',
    iosClientId: '481537812306-1e2v1mbipadg57fc8qpdac1ku7lc306p.apps.googleusercontent.com',
    iosBundleId: 'com.example.apecNoDues',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYVItWTIh3n99sQOu21FSkR3c9CTY_4bQ',
    appId: '1:481537812306:ios:ef13a5af01f326cc8b3c8b',
    messagingSenderId: '481537812306',
    projectId: 'apec-no-dues',
    storageBucket: 'apec-no-dues.firebasestorage.app',
    iosClientId: '481537812306-1e2v1mbipadg57fc8qpdac1ku7lc306p.apps.googleusercontent.com',
    iosBundleId: 'com.example.apecNoDues',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBHlVtdqEHy7LyGsBPPNnylRxbV8nBjB0',
    appId: '1:481537812306:web:82dd7adfe91be0cd8b3c8b',
    messagingSenderId: '481537812306',
    projectId: 'apec-no-dues',
    authDomain: 'apec-no-dues.firebaseapp.com',
    storageBucket: 'apec-no-dues.firebasestorage.app',
    measurementId: 'G-6YZHBHLZEJ',
  );
}
