import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'firebase_options.dart'; // Generated by 'flutterfire configure'

// Screens
import 'screens/login_screen.dart';
import 'screens/student/student_dashboard.dart';
import 'screens/admin/admin_dashboard.dart';
import 'screens/staff/staff_dashboard.dart';
import 'screens/cert_verify_screen.dart';

// Services
import 'services/notification_service.dart';
import 'services/activity_tracker.dart';
import 'services/auth_service.dart';
import 'screens/splash_screen.dart';

// Global Key for ScaffoldMessenger to show notifications from anywhere
final GlobalKey<ScaffoldMessengerState> messengerKey = GlobalKey<ScaffoldMessengerState>();
// Global Key for Navigator to perform navigation from anywhere
final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Firebase with error handling
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    
    // Initialize notification service
    await NotificationService().initialize();
    
    // Initialize activity tracker
    ActivityTracker().initialize();
    
    // Ensure Master Admin Exists (Seeding)
    await AuthService().ensureMasterAdminExists();
    
  } catch (e) {
    print("Firebase Initialization Error: $e");
  }

  runApp(const ADACSApp());
}

class ADACSApp extends StatefulWidget {
  const ADACSApp({super.key});

  @override
  State<ADACSApp> createState() => _ADACSAppState();
}

class _ADACSAppState extends State<ADACSApp> with WidgetsBindingObserver {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    // Update badge count on app launch (after a short delay so auth resolves)
    Future.delayed(const Duration(seconds: 2), () async {
      await NotificationService().updateAppBadge();
      // also fire a launch notification so the shade shows our app name/text
      await NotificationService().showLaunchNotification();
    });
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    // Refresh badge count every time user brings the app back to foreground
    if (state == AppLifecycleState.resumed) {
      NotificationService().updateAppBadge();
      NotificationService().showLaunchNotification();
    }
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'A-DACS',
      debugShowCheckedModeBanner: false,
      navigatorKey: navigatorKey,
      scaffoldMessengerKey: messengerKey,
      theme: ThemeData(
        primarySwatch: Colors.indigo,
        scaffoldBackgroundColor: Colors.grey[50],
        appBarTheme: const AppBarTheme(
          backgroundColor: Colors.indigo,
          foregroundColor: Colors.white,
          centerTitle: true,
          elevation: 0,
        ),
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: Colors.indigo,
            foregroundColor: Colors.white,
            padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
          ),
        ),
        inputDecorationTheme: const InputDecorationTheme(
          border: OutlineInputBorder(),
          contentPadding: EdgeInsets.symmetric(horizontal: 16, vertical: 16),
        ),
      ),
      home: const SplashScreen(),
      onGenerateRoute: (settings) {
        final uri = Uri.tryParse(settings.name ?? '');
        if (uri != null && uri.path == '/verify') {
          final certId = uri.queryParameters['id'] ?? '';
          return MaterialPageRoute(
            builder: (_) => CertVerifyScreen(certId: certId),
            settings: settings,
          );
        }
        return null;
      },
    );
  }
}

/// This widget listens to the Auth State (Logged In vs Logged Out)
class AuthWrapper extends StatelessWidget {
  const AuthWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        // 1. If waiting for connection
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(body: Center(child: CircularProgressIndicator()));
        }

        // 2. If User is Logged In -> Determine Role & Route
        if (snapshot.hasData && snapshot.data != null) {
          return const RoleResolver();
        }

        // 3. If User is Logged Out -> Show Login Screen
        return const LoginScreen();
      },
    );
  }
}

/// Fetches the User's Role from Firestore to decide which Dashboard to show
class RoleResolver extends StatelessWidget {
  const RoleResolver({super.key});

  @override
  Widget build(BuildContext context) {
    final User user = FirebaseAuth.instance.currentUser!;

    return FutureBuilder<DocumentSnapshot>(
      future: FirebaseFirestore.instance.collection('users').doc(user.uid).get(),
      builder: (context, snapshot) {
        // Loading State
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  CircularProgressIndicator(),
                  SizedBox(height: 20),
                  Text("Fetching Profile..."),
                ],
              ),
            ),
          );
        }

        // Error or No Data
        if (snapshot.hasError || !snapshot.hasData || !snapshot.data!.exists) {
          return Scaffold(
            body: Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  const Icon(Icons.error_outline, size: 50, color: Colors.red),
                  const SizedBox(height: 10),
                  const Text("Error fetching user profile."),
                  TextButton(
                    onPressed: () => FirebaseAuth.instance.signOut(), 
                    child: const Text("Logout & Try Again")
                  ),
                ],
              ),
            ),
          );
        }

        // Data Loaded -> Check Role
        final data = snapshot.data!.data() as Map<String, dynamic>;
        final String role = data['role'] ?? 'student';

        // Update app icon badge count now that we know who is logged in
        NotificationService().updateAppBadge();

        if (role == 'admin') {
          return const AdminDashboard();
        } else if (role == 'staff') {
          return const StaffDashboard();
        } else {
          return const StudentDashboard();
        }
      },
    );
  }
}